name: CI

on: [ push, pull_request ]

jobs:
  build-linux:
    timeout-minutes: 20
    runs-on: [ubuntu-latest, macOS-latest]

    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v2
      
      - name: install bake
        run: |
          git clone https://github.com/SanderMertens/bake
          make -C bake/build-$(uname)
          bake/bake setup

      - name: build
        run: bake
